---
- name: Download Vault binary
  get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "/tmp/vault.zip"

- name: Unzip Vault binary
  unarchive:
    src: "/tmp/vault.zip"
    dest: "/usr/local/bin/"
    remote_src: True

- name: Create Vault config directory
  file: 
    state=directory
    path=/etc/vault/

- name: Copy Vault config to server
  copy: 
    src=vaultconfig.hcl
    dest=/etc/vault/config.hcl

- name: Copy Vault service to server
  copy: 
    src=vault.service
    dest=/etc/systemd/system/vault.service

- name: Enable and Start Vault service
  systemd:
    name: vault
    state: started
    daemon_reload: yes

- pause:
    seconds: 15

- name: Initialize the Vault
  command: vault operator init
  register: keys

- debug: msg="{{ keys }}"